### ISSUE TITLE
Selecting data

### ISSUE THREAD

**Issue by aimalz** [marin-hyatt/redshift_data_project#4]
You'll need to learn some "data janitorial" work to get rid of the -9999 and 0.0 values that indicate untrustworthy measurements, since you've seen that they can bias your results.  Try repeating the analysis with the dataset remaining after you filter out those galaxies.  I recommend you check out lialubit/Redshift/#4 to work with @lialubit on learning how to do that.

**Comment by marin-hyatt** [comment]
Hi, I have a couple questions. Lia and I have found a few different methods of filtering data. The first one we tried was the query method, which worked for Lia but for me it said that the name "redshift" wasn't defined. I then tried the .isin() method which didn't return an error but also didn't seem to work. I expected it to return another dataframe but it returned a weirdly formatted table (?) that didn't really tell me anything. I don't really know what's going on or where to go so any advice would be appreciated. I'm thinking since Lia and I obtained our dataframes differently (I used .read.csv() and she used .DataFrame()) that might be the issue? Anyway, any help or advice would be appreciated!

**Comment by marin-hyatt** [comment]
I tried researching the problem and trying out different methods. I probably shouldn't have done this out of mercy for my machine, but I printed out df.index.tolist(), which gave me a huge list of not only the headings like objid and redshift, but pretty much every other number too. I don't really know why it did that. Still, this doesn't make sense because when I try to just print the column u, it shows an error which says that label [u] is not in the [index]. I'm a little confused, because I literally just saw it there. Anyway, I made a little progress but I still need help. Maybe I'm missing something?

EDIT: I realized I needed to specify some things concerning how pandas was reading the csv file. Now I got the filter to work! Except according to the filter, there are no rows in the csv file that have a redshift value of 0.00 and a magnitude of -9999. Is this supposed to happen?

**Comment by aimalz** [comment]
Sorry for taking so long to respond!  Check out [this gist](https://gist.github.com/aimalz/f4e6ab7e976ea214815a23ef690383ff) for examples.

I think the first problem can be solved with keyword arguments to `pd.read_csv`, but it looks like you figured that out before I replied.  (That's awesome!)

It's possible that in a small sample of data like yours, you might not encounter any placeholder values.  One way to check is to make diagnostic plots -- @lialubit now knows a lot of tricks for exploratory data analysis if you want to compare notes -- so you could get an overview of what kind of anomalies might be lurking in your dataset.  Based on those, I see at least one "bad value" in the `i` and `z` bands, although you can't tell for the redshifts without knowing the likely placeholder values for this dataset in particular, i.e. diagnostic plots aren't foolproof.  Once you know what values to look for, you can pick out those rows by their indices by matching a condition.

(And I'm sure there are other ways to solve these problems.  I'm looking forward to learning from your unique solutions, too.)

**Comment by marin-hyatt** [comment]
I used your gist to find out what names had outliers. It turns out that i and z both have values of -9999, but when I try to filter out those values, I still get an empty dataframe. I'm a little confused, so advice would be appreciated! Thanks for helping me so much.

**Comment by aimalz** [comment]
Sure, let's figure this out!  ~~Can you update the jupyter notebook on GitHub so I can take a look?~~ Whoops, I failed to see that you already did so!  I'll get back to you soon.

**Comment by aimalz** [comment]
I doubt [this](https://gist.github.com/aimalz/3760ea31817ab14d2af9f1862cfb303d) will help, but let's try just in case.

**Comment by aimalz** [comment]
Let's try fiddling with the [tick marks](https://matplotlib.org/users/dflt_style_changes.html#plot-layout).

**Comment by aimalz** [comment]
So we don't forget later: plotting a histogram of string versions of floats will probably give a flat histogram because the strings are likely unique.  Also, we're stumped by why `matplotlib` config parameters don't update once they've been specified. . .

In any case, congrats @marin-hyatt on filtering the data!
